// Mock data for deals and market companies
export const initialDeals = [
  {
    id: "hvac",
    name: "HVAC Co. Acquisition",
    type: "buy",
    stage: "Due Diligence",
    health: 85,
    lastActivity: "Document received 2m ago",
  },
  {
    id: "storage",
    name: "Public Storage Investment",
    type: "buy",
    stage: "Initial Review",
    health: 92,
    lastActivity: "Report updated 3h ago",
  },
  {
    id: "acme",
    name: "Acme Air Conditioning",
    type: "sell",
    stage: "Closing",
    health: 72,
    lastActivity: "Client replied 1h ago",
  },
  {
    id: "lacy",
    name: "Lacy's Laundromat Merger",
    type: "buy",
    stage: "Sourcing",
    health: 65,
    lastActivity: "New task added yesterday",
  },
]

export const marketDeals = [
  {
    id: "tech-startup-alpha",
    name: "TechFlow Solutions",
    ticker: "TECH",
    industry: "SaaS",
    location: "Austin, TX",
    revenue: "$2.4M",
    employees: 24,
    founded: 2019,
    website: "techflow.com",
    linkedin: "linkedin.com/company/techflow-solutions",
    description: "AI-powered workflow automation platform",
    ebitda: "$720K",
    multiple: "8.2x",
    health: 88,
    peRollupScore: "High",
    creditScore: "A+",
    keyMetrics: {
      growth: "+145%",
      retention: "98%",
      margins: "42%",
    },
    highlights: ["Strong recurring revenue model", "Proven market traction", "Experienced management team"],
  },
  {
    id: "manufacturing-beta",
    name: "Precision Manufacturing Co.",
    ticker: "PMC",
    industry: "Manufacturing",
    location: "Detroit, MI",
    revenue: "$12.8M",
    employees: 85,
    founded: 2015,
    website: "precisionmfg.com",
    linkedin: "linkedin.com/company/precision-manufacturing",
    description: "Specialized automotive parts manufacturer",
    ebitda: "$3.2M",
    multiple: "5.1x",
    health: 76,
    peRollupScore: "Medium",
    creditScore: "A-",
    keyMetrics: {
      growth: "+28%",
      retention: "95%",
      margins: "25%",
    },
    highlights: ["Long-term contracts with OEMs", "Modern manufacturing facilities", "Strong operational efficiency"],
  },
  {
    id: "healthcare-gamma",
    name: "MedTech Innovations",
    ticker: "MEDI",
    industry: "Healthcare",
    location: "Boston, MA",
    revenue: "$5.6M",
    employees: 42,
    founded: 2018,
    website: "medtech-innov.com",
    linkedin: "linkedin.com/company/medtech-innovations",
    description: "Medical device technology solutions",
    ebitda: "$1.4M",
    multiple: "12.5x",
    health: 91,
    peRollupScore: "High",
    creditScore: "A+",
    keyMetrics: {
      growth: "+89%",
      retention: "94%",
      margins: "38%",
    },
    highlights: ["FDA-approved products", "Strong IP portfolio", "Experienced R&D team"],
  },
  {
    id: "retail-delta",
    name: "Urban Retail Group",
    ticker: "URG",
    industry: "Retail",
    location: "Los Angeles, CA",
    revenue: "$8.2M",
    employees: 156,
    founded: 2016,
    website: "urbanretail.com",
    linkedin: "linkedin.com/company/urban-retail-group",
    description: "Multi-brand retail chain operations",
    ebitda: "$1.6M",
    multiple: "6.8x",
    health: 72,
    peRollupScore: "Low",
    creditScore: "B+",
    keyMetrics: {
      growth: "+34%",
      retention: "87%",
      margins: "19%",
    },
    highlights: ["Prime retail locations", "Strong brand partnerships", "Omnichannel presence"],
  },
  {
    id: "fintech-epsilon",
    name: "PayStream Solutions",
    ticker: "PAY",
    industry: "Financial Services",
    location: "New York, NY",
    revenue: "$15.3M",
    employees: 68,
    founded: 2017,
    website: "paystream.io",
    linkedin: "linkedin.com/company/paystream-solutions",
    description: "B2B payment processing platform",
    ebitda: "$4.6M",
    multiple: "9.2x",
    health: 85,
    peRollupScore: "High",
    creditScore: "A",
    keyMetrics: {
      growth: "+67%",
      retention: "96%",
      margins: "30%",
    },
    highlights: ["Enterprise client base", "Regulatory compliance", "Scalable infrastructure"],
  },
  {
    id: "logistics-zeta",
    name: "Swift Logistics Inc.",
    ticker: "SWFT",
    industry: "Logistics",
    location: "Chicago, IL",
    revenue: "$22.1M",
    employees: 234,
    founded: 2014,
    website: "swiftlogistics.com",
    linkedin: "linkedin.com/company/swift-logistics",
    description: "Last-mile delivery and warehousing",
    ebitda: "$3.8M",
    multiple: "4.9x",
    health: 79,
    peRollupScore: "Medium",
    creditScore: "A-",
    keyMetrics: {
      growth: "+41%",
      retention: "91%",
      margins: "17%",
    },
    highlights: ["Regional market leader", "Modern fleet", "Technology-driven operations"],
  },
  {
    id: "energy-eta",
    name: "GreenTech Energy",
    ticker: "GTE",
    industry: "Energy",
    location: "Denver, CO",
    revenue: "$18.7M",
    employees: 127,
    founded: 2015,
    website: "greentech-energy.com",
    linkedin: "linkedin.com/company/greentech-energy",
    description: "Renewable energy solutions provider",
    ebitda: "$5.2M",
    multiple: "7.3x",
    health: 88,
    peRollupScore: "High",
    creditScore: "A",
    keyMetrics: {
      growth: "+78%",
      retention: "93%",
      margins: "28%",
    },
    highlights: ["Government contracts", "Sustainable technology", "Growing market demand"],
  },
  {
    id: "software-theta",
    name: "DataViz Pro",
    ticker: "DVP",
    industry: "Technology",
    location: "Seattle, WA",
    revenue: "$6.8M",
    employees: 38,
    founded: 2019,
    website: "datavizpro.com",
    linkedin: "linkedin.com/company/dataviz-pro",
    description: "Business intelligence and analytics",
    ebitda: "$2.1M",
    multiple: "11.4x",
    health: 92,
    peRollupScore: "High",
    creditScore: "A+",
    keyMetrics: {
      growth: "+156%",
      retention: "97%",
      margins: "31%",
    },
    highlights: ["Enterprise SaaS model", "Strong customer retention", "AI-powered insights"],
  },
  {
    id: "food-iota",
    name: "Artisan Foods Co.",
    ticker: "AFC",
    industry: "Food & Beverage",
    location: "Portland, OR",
    revenue: "$9.3M",
    employees: 67,
    founded: 2016,
    website: "artisanfoods.com",
    linkedin: "linkedin.com/company/artisan-foods",
    description: "Organic specialty food manufacturer",
    ebitda: "$2.1M",
    multiple: "6.2x",
    health: 81,
    peRollupScore: "Medium",
    creditScore: "A-",
    keyMetrics: {
      growth: "+52%",
      retention: "89%",
      margins: "23%",
    },
    highlights: ["Organic certification", "Regional distribution", "Premium brand positioning"],
  },
  {
    id: "construction-kappa",
    name: "BuildRight Construction",
    ticker: "BRC",
    industry: "Construction",
    location: "Phoenix, AZ",
    revenue: "$28.4M",
    employees: 189,
    founded: 2012,
    website: "buildright.com",
    linkedin: "linkedin.com/company/buildright-construction",
    description: "Commercial construction and development",
    ebitda: "$4.2M",
    multiple: "4.8x",
    health: 74,
    peRollupScore: "Low",
    creditScore: "B+",
    keyMetrics: {
      growth: "+31%",
      retention: "92%",
      margins: "15%",
    },
    highlights: ["Strong project pipeline", "Licensed in 5 states", "Safety record excellence"],
  },
  {
    id: "education-lambda",
    name: "EduTech Academy",
    ticker: "ETA",
    industry: "Education",
    location: "Atlanta, GA",
    revenue: "$4.7M",
    employees: 34,
    founded: 2018,
    website: "edutech-academy.com",
    linkedin: "linkedin.com/company/edutech-academy",
    description: "Online learning platform for professionals",
    ebitda: "$1.8M",
    multiple: "9.8x",
    health: 87,
    peRollupScore: "High",
    creditScore: "A",
    keyMetrics: {
      growth: "+124%",
      retention: "94%",
      margins: "38%",
    },
    highlights: ["Accredited courses", "Corporate partnerships", "High completion rates"],
  },
  {
    id: "automotive-mu",
    name: "AutoParts Direct",
    ticker: "APD",
    industry: "Automotive",
    location: "Cleveland, OH",
    revenue: "$16.2M",
    employees: 98,
    founded: 2014,
    website: "autopartsdirect.com",
    linkedin: "linkedin.com/company/autoparts-direct",
    description: "Aftermarket automotive parts distributor",
    ebitda: "$3.4M",
    multiple: "5.6x",
    health: 78,
    peRollupScore: "Medium",
    creditScore: "A-",
    keyMetrics: {
      growth: "+38%",
      retention: "88%",
      margins: "21%",
    },
    highlights: ["National distribution network", "OEM partnerships", "Inventory management system"],
  },
  {
    id: "real-estate-nu",
    name: "PropTech Solutions",
    ticker: "PTS",
    industry: "Real Estate",
    location: "Miami, FL",
    revenue: "$7.8M",
    employees: 45,
    founded: 2017,
    website: "proptech-sol.com",
    linkedin: "linkedin.com/company/proptech-solutions",
    description: "Property management software platform",
    ebitda: "$2.3M",
    multiple: "8.9x",
    health: 84,
    peRollupScore: "High",
    creditScore: "A",
    keyMetrics: {
      growth: "+73%",
      retention: "96%",
      margins: "29%",
    },
    highlights: ["SaaS model", "Multi-family focus", "Mobile-first platform"],
  },
  {
    id: "agriculture-xi",
    name: "AgriTech Innovations",
    ticker: "ATI",
    industry: "Agriculture",
    location: "Des Moines, IA",
    revenue: "$11.5M",
    employees: 76,
    founded: 2015,
    website: "agritech-innov.com",
    linkedin: "linkedin.com/company/agritech-innovations",
    description: "Precision agriculture technology",
    ebitda: "$2.8M",
    multiple: "7.1x",
    health: 82,
    peRollupScore: "Medium",
    creditScore: "A-",
    keyMetrics: {
      growth: "+45%",
      retention: "91%",
      margins: "24%",
    },
    highlights: ["IoT sensors", "Data analytics platform", "Farmer partnerships"],
  },
  {
    id: "chemicals-omicron",
    name: "Specialty Chemicals Inc.",
    ticker: "SCI",
    industry: "Chemicals",
    location: "Houston, TX",
    revenue: "$34.6M",
    employees: 156,
    founded: 2011,
    website: "specialtychem.com",
    linkedin: "linkedin.com/company/specialty-chemicals",
    description: "Industrial specialty chemicals manufacturer",
    ebitda: "$8.2M",
    multiple: "4.2x",
    health: 76,
    peRollupScore: "Medium",
    creditScore: "A-",
    keyMetrics: {
      growth: "+22%",
      retention: "94%",
      margins: "24%",
    },
    highlights: ["EPA compliance", "Long-term contracts", "R&D capabilities"],
  },
  {
    id: "telecom-pi",
    name: "ConnectWave Telecom",
    ticker: "CWT",
    industry: "Telecommunications",
    location: "Raleigh, NC",
    revenue: "$19.3M",
    employees: 112,
    founded: 2013,
    website: "connectwave.com",
    linkedin: "linkedin.com/company/connectwave-telecom",
    description: "Regional telecommunications provider",
    ebitda: "$5.8M",
    multiple: "3.9x",
    health: 79,
    peRollupScore: "Medium",
    creditScore: "A-",
    keyMetrics: {
      growth: "+29%",
      retention: "96%",
      margins: "30%",
    },
    highlights: ["Fiber network", "Business customers", "5G infrastructure"],
  },
  {
    id: "aerospace-rho",
    name: "AeroComponents Ltd.",
    ticker: "ACL",
    industry: "Aerospace",
    location: "Wichita, KS",
    revenue: "$42.1M",
    employees: 234,
    founded: 2009,
    website: "aerocomponents.com",
    linkedin: "linkedin.com/company/aerocomponents",
    description: "Aircraft component manufacturing",
    ebitda: "$9.8M",
    multiple: "4.6x",
    health: 83,
    peRollupScore: "High",
    creditScore: "A",
    keyMetrics: {
      growth: "+18%",
      retention: "97%",
      margins: "23%",
    },
    highlights: ["FAA certified", "Defense contracts", "Quality certifications"],
  },
  {
    id: "textiles-sigma",
    name: "Premium Textiles Co.",
    ticker: "PTC",
    industry: "Textiles",
    location: "Charlotte, NC",
    revenue: "$13.7M",
    employees: 89,
    founded: 2014,
    website: "premiumtextiles.com",
    linkedin: "linkedin.com/company/premium-textiles",
    description: "High-end textile manufacturing",
    ebitda: "$2.9M",
    multiple: "5.8x",
    health: 77,
    peRollupScore: "Low",
    creditScore: "B+",
    keyMetrics: {
      growth: "+35%",
      retention: "86%",
      margins: "21%",
    },
    highlights: ["Sustainable materials", "Fashion partnerships", "Custom manufacturing"],
  },
  {
    id: "gaming-tau",
    name: "GameStudio Interactive",
    ticker: "GSI",
    industry: "Gaming",
    location: "San Francisco, CA",
    revenue: "$8.9M",
    employees: 52,
    founded: 2017,
    website: "gamestudio.com",
    linkedin: "linkedin.com/company/gamestudio-interactive",
    description: "Mobile game development studio",
    ebitda: "$3.1M",
    multiple: "10.2x",
    health: 89,
    peRollupScore: "High",
    creditScore: "A",
    keyMetrics: {
      growth: "+98%",
      retention: "92%",
      margins: "35%",
    },
    highlights: ["Hit mobile games", "In-app monetization", "Global user base"],
  },
  {
    id: "security-upsilon",
    name: "CyberShield Security",
    ticker: "CSS",
    industry: "Cybersecurity",
    location: "Washington, DC",
    revenue: "$12.4M",
    employees: 67,
    founded: 2016,
    website: "cybershield.com",
    linkedin: "linkedin.com/company/cybershield-security",
    description: "Enterprise cybersecurity solutions",
    ebitda: "$3.7M",
    multiple: "8.7x",
    health: 91,
    peRollupScore: "High",
    creditScore: "A+",
    keyMetrics: {
      growth: "+87%",
      retention: "98%",
      margins: "30%",
    },
    highlights: ["Government contracts", "SOC 2 compliance", "24/7 monitoring"],
  },
  {
    id: "pharma-phi",
    name: "BioMed Research Corp.",
    ticker: "BMR",
    industry: "Pharmaceuticals",
    location: "San Diego, CA",
    revenue: "$25.8M",
    employees: 143,
    founded: 2012,
    website: "biomedresearch.com",
    linkedin: "linkedin.com/company/biomed-research",
    description: "Pharmaceutical research and development",
    ebitda: "$6.2M",
    multiple: "11.8x",
    health: 86,
    peRollupScore: "High",
    creditScore: "A",
    keyMetrics: {
      growth: "+42%",
      retention: "95%",
      margins: "24%",
    },
    highlights: ["FDA pipeline", "Patent portfolio", "Clinical trials"],
  },
  {
    id: "marine-chi",
    name: "Oceanic Solutions",
    ticker: "OSL",
    industry: "Marine",
    location: "Seattle, WA",
    revenue: "$17.6M",
    employees: 98,
    founded: 2013,
    website: "oceanicsol.com",
    linkedin: "linkedin.com/company/oceanic-solutions",
    description: "Marine equipment and services",
    ebitda: "$4.1M",
    multiple: "5.3x",
    health: 80,
    peRollupScore: "Medium",
    creditScore: "A-",
    keyMetrics: {
      growth: "+33%",
      retention: "89%",
      margins: "23%",
    },
    highlights: ["Coast Guard certified", "Commercial fishing", "Maintenance services"],
  },
  {
    id: "fitness-psi",
    name: "FitTech Solutions",
    ticker: "FTS",
    industry: "Fitness",
    location: "Los Angeles, CA",
    revenue: "$6.2M",
    employees: 41,
    founded: 2018,
    website: "fittech-sol.com",
    linkedin: "linkedin.com/company/fittech-solutions",
    description: "Fitness technology and equipment",
    ebitda: "$1.9M",
    multiple: "9.1x",
    health: 85,
    peRollupScore: "High",
    creditScore: "A-",
    keyMetrics: {
      growth: "+76%",
      retention: "93%",
      margins: "31%",
    },
    highlights: ["Connected equipment", "Subscription model", "Health tracking"],
  },
  {
    id: "packaging-omega",
    name: "EcoPack Industries",
    ticker: "EPI",
    industry: "Packaging",
    location: "Nashville, TN",
    revenue: "$21.3M",
    employees: 134,
    founded: 2014,
    website: "ecopack.com",
    linkedin: "linkedin.com/company/ecopack-industries",
    description: "Sustainable packaging solutions",
    ebitda: "$4.7M",
    multiple: "5.9x",
    health: 78,
    peRollupScore: "Medium",
    creditScore: "A-",
    keyMetrics: {
      growth: "+39%",
      retention: "91%",
      margins: "22%",
    },
    highlights: ["Biodegradable materials", "Custom solutions", "Food grade certified"],
  },
  {
    id: "insurance-alpha2",
    name: "RiskGuard Insurance",
    ticker: "RGI",
    industry: "Insurance",
    location: "Hartford, CT",
    revenue: "$31.4M",
    employees: 187,
    founded: 2011,
    website: "riskguard.com",
    linkedin: "linkedin.com/company/riskguard-insurance",
    description: "Commercial insurance brokerage",
    ebitda: "$7.8M",
    multiple: "4.1x",
    health: 82,
    peRollupScore: "Medium",
    creditScore: "A",
    keyMetrics: {
      growth: "+26%",
      retention: "94%",
      margins: "25%",
    },
    highlights: ["Licensed nationwide", "Risk assessment tools", "Claims management"],
  },
  {
    id: "hospitality-beta2",
    name: "Boutique Hotels Group",
    ticker: "BHG",
    industry: "Hospitality",
    location: "Charleston, SC",
    revenue: "$18.9M",
    employees: 245,
    founded: 2015,
    website: "boutiquehotels.com",
    linkedin: "linkedin.com/company/boutique-hotels-group",
    description: "Luxury boutique hotel operations",
    ebitda: "$3.8M",
    multiple: "6.7x",
    health: 75,
    peRollupScore: "Low",
    creditScore: "B+",
    keyMetrics: {
      growth: "+28%",
      retention: "87%",
      margins: "20%",
    },
    highlights: ["Prime locations", "High occupancy rates", "Luxury amenities"],
  },
  {
    id: "media-gamma2",
    name: "Digital Media Works",
    ticker: "DMW",
    industry: "Media",
    location: "New York, NY",
    revenue: "$9.7M",
    employees: 58,
    founded: 2017,
    website: "digitalmedia.com",
    linkedin: "linkedin.com/company/digital-media-works",
    description: "Digital content creation and marketing",
    ebitda: "$2.8M",
    multiple: "8.4x",
    health: 88,
    peRollupScore: "High",
    creditScore: "A",
    keyMetrics: {
      growth: "+65%",
      retention: "95%",
      margins: "29%",
    },
    highlights: ["Creative agency", "Brand partnerships", "Multi-platform content"],
  },
  {
    id: "transportation-delta2",
    name: "FleetMax Transportation",
    ticker: "FMT",
    industry: "Transportation",
    location: "Dallas, TX",
    revenue: "$26.7M",
    employees: 178,
    founded: 2013,
    website: "fleetmax.com",
    linkedin: "linkedin.com/company/fleetmax-transportation",
    description: "Commercial transportation services",
    ebitda: "$5.3M",
    multiple: "4.7x",
    health: 81,
    peRollupScore: "Medium",
    creditScore: "A-",
    keyMetrics: {
      growth: "+32%",
      retention: "90%",
      margins: "20%",
    },
    highlights: ["Regional coverage", "Fleet management", "Safety certifications"],
  },
  {
    id: "consulting-epsilon2",
    name: "Strategic Advisors LLC",
    ticker: "SAL",
    industry: "Consulting",
    location: "Chicago, IL",
    revenue: "$14.2M",
    employees: 89,
    founded: 2016,
    website: "strategicadv.com",
    linkedin: "linkedin.com/company/strategic-advisors",
    description: "Management consulting services",
    ebitda: "$4.3M",
    multiple: "7.2x",
    health: 84,
    peRollupScore: "High",
    creditScore: "A",
    keyMetrics: {
      growth: "+48%",
      retention: "96%",
      margins: "30%",
    },
    highlights: ["Fortune 500 clients", "Industry expertise", "Digital transformation"],
  },
  {
    id: "biotech-zeta2",
    name: "GeneTech Laboratories",
    ticker: "GTL",
    industry: "Biotechnology",
    location: "Cambridge, MA",
    revenue: "$19.8M",
    employees: 112,
    founded: 2014,
    website: "genetech-labs.com",
    linkedin: "linkedin.com/company/genetech-laboratories",
    description: "Genetic testing and research services",
    ebitda: "$5.9M",
    multiple: "9.6x",
    health: 90,
    peRollupScore: "High",
    creditScore: "A+",
    keyMetrics: {
      growth: "+71%",
      retention: "97%",
      margins: "30%",
    },
    highlights: ["CLIA certified", "Research partnerships", "Proprietary technology"],
  },
  {
    id: "renewable-eta2",
    name: "SolarWind Energy Co.",
    ticker: "SWE",
    industry: "Renewable Energy",
    location: "Austin, TX",
    revenue: "$23.4M",
    employees: 145,
    founded: 2015,
    website: "solarwind.com",
    linkedin: "linkedin.com/company/solarwind-energy",
    description: "Solar and wind energy development",
    ebitda: "$6.8M",
    multiple: "6.4x",
    health: 87,
    peRollupScore: "High",
    creditScore: "A",
    keyMetrics: {
      growth: "+56%",
      retention: "92%",
      margins: "29%",
    },
    highlights: ["Utility partnerships", "Tax credit optimization", "Grid integration"],
  },
  {
    id: "robotics-theta2",
    name: "AutoBot Robotics",
    ticker: "ABR",
    industry: "Robotics",
    location: "Pittsburgh, PA",
    revenue: "$15.6M",
    employees: 87,
    founded: 2016,
    website: "autobot-robotics.com",
    linkedin: "linkedin.com/company/autobot-robotics",
    description: "Industrial automation and robotics",
    ebitda: "$4.2M",
    multiple: "8.1x",
    health: 86,
    peRollupScore: "High",
    creditScore: "A",
    keyMetrics: {
      growth: "+62%",
      retention: "94%",
      margins: "27%",
    },
    highlights: ["Manufacturing automation", "AI integration", "Custom solutions"],
  },
  {
    id: "water-iota2",
    name: "AquaTech Systems",
    ticker: "ATS",
    industry: "Water Treatment",
    location: "Phoenix, AZ",
    revenue: "$12.9M",
    employees: 74,
    founded: 2015,
    website: "aquatech-sys.com",
    linkedin: "linkedin.com/company/aquatech-systems",
    description: "Water treatment and purification systems",
    ebitda: "$3.1M",
    multiple: "6.8x",
    health: 83,
    peRollupScore: "Medium",
    creditScore: "A-",
    keyMetrics: {
      growth: "+41%",
      retention: "88%",
      margins: "24%",
    },
    highlights: ["Municipal contracts", "Environmental compliance", "Maintenance services"],
  },
  {
    id: "mining-kappa2",
    name: "Precision Mining Corp.",
    ticker: "PMC2",
    industry: "Mining",
    location: "Denver, CO",
    revenue: "$38.7M",
    employees: 198,
    founded: 2012,
    website: "precisionmining.com",
    linkedin: "linkedin.com/company/precision-mining",
    description: "Specialty minerals extraction",
    ebitda: "$9.2M",
    multiple: "4.3x",
    health: 79,
    peRollupScore: "Medium",
    creditScore: "A-",
    keyMetrics: {
      growth: "+24%",
      retention: "91%",
      margins: "24%",
    },
    highlights: ["Rare earth minerals", "Environmental permits", "Export capabilities"],
  },
  {
    id: "veterinary-lambda2",
    name: "VetCare Solutions",
    ticker: "VCS",
    industry: "Veterinary",
    location: "Nashville, TN",
    revenue: "$8.4M",
    employees: 56,
    founded: 2017,
    website: "vetcare-sol.com",
    linkedin: "linkedin.com/company/vetcare-solutions",
    description: "Veterinary practice management software",
    ebitda: "$2.5M",
    multiple: "9.3x",
    health: 85,
    peRollupScore: "High",
    creditScore: "A",
    keyMetrics: {
      growth: "+83%",
      retention: "96%",
      margins: "30%",
    },
    highlights: ["Cloud-based platform", "Mobile app", "Practice analytics"],
  },
  {
    id: "printing-mu2",
    name: "Digital Print Solutions",
    ticker: "DPS",
    industry: "Printing",
    location: "Minneapolis, MN",
    revenue: "$16.8M",
    employees: 102,
    founded: 2014,
    website: "digitalprint.com",
    linkedin: "linkedin.com/company/digital-print-solutions",
    description: "Commercial digital printing services",
    ebitda: "$3.6M",
    multiple: "5.4x",
    health: 77,
    peRollupScore: "Low",
    creditScore: "B+",
    keyMetrics: {
      growth: "+29%",
      retention: "85%",
      margins: "21%",
    },
    highlights: ["Large format printing", "Quick turnaround", "Design services"],
  },
  {
    id: "waste-nu2",
    name: "EcoWaste Management",
    ticker: "EWM",
    industry: "Waste Management",
    location: "Portland, OR",
    revenue: "$22.6M",
    employees: 156,
    founded: 2013,
    website: "ecowaste.com",
    linkedin: "linkedin.com/company/ecowaste-management",
    description: "Sustainable waste management solutions",
    ebitda: "$5.4M",
    multiple: "4.9x",
    health: 80,
    peRollupScore: "Medium",
    creditScore: "A-",
    keyMetrics: {
      growth: "+36%",
      retention: "93%",
      margins: "24%",
    },
    highlights: ["Recycling programs", "Municipal contracts", "Zero waste initiatives"],
  },
]

export const activityFeedData = [
  {
    id: 1,
    type: "document",
    title: "New document received",
    description: "Q4 2023 P&L Statement for HVAC Co.",
    timestamp: "2m ago",
    date: "Today",
  },
  {
    id: 2,
    type: "reply",
    title: "New reply from Acme Air",
    description: "Client has responded to the request for the QoE Report.",
    timestamp: "1h ago",
    date: "Today",
  },
  {
    id: 3,
    type: "report",
    title: "Report updated",
    description: "Financial Performance Analysis for Public Storage is complete.",
    timestamp: "3h ago",
    date: "Today",
  },
  {
    id: 4,
    type: "task",
    title: "New task added",
    description: "Review new cybersecurity audit for HVAC Co.",
    timestamp: "Yesterday",
    date: "Yesterday",
  },
  {
    id: 5,
    type: "deal",
    title: "New deal request received",
    description: "Project Alpha - Tech Startup",
    timestamp: "Yesterday",
    date: "Yesterday",
  },
]
